//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushAll.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushAllUser
    {
        public string UserId { get; set; }
        public string PushAllUserId { get; set; }
    }
}
